#coding=utf-8
print('Hello world!')
# print("hello Again")
# print("I like typing this.")
# print("This is fun.")
# print('Yay!Printing.')
# print("I'd much rather you 'not'.")
# print('I "said" do not touch this.')
# print("I like programing.")
print("我是中国人")